language: php

jobs:
  include:
  - stage: Unit tests
  - env:
    php: 5.6
  - env: COMPOSER_FLAGS="--prefer-lowest"
    php: 5.6
  - env:
    php: 7.0
  - env: COMPOSER_FLAGS="--prefer-lowest"
    php: 7.0
  - env:
    php: 7.1
  - env: COMPOSER_FLAGS="--prefer-lowest"
    php: 7.1
  - env:
    php: 7.2
  - env: COMPOSER_FLAGS="--prefer-lowest"
    php: 7.2
  - env:
    php: 7.3
  - env: COMPOSER_FLAGS="--prefer-lowest"
    php: 7.3

before_install:
- composer self-update

install:
- composer update -o $COMPOSER_FLAGS

script:
- ./vendor/bin/phpunit

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
