language: php

matrix:
  fast_finish: true
  include:
  - env: TEST_DIR=.
    php: 5.6
  - env: TEST_DIR=. COMPOSER_FLAGS="--prefer-lowest"
    php: 5.6
  - env: TEST_DIR=.
    php: 7.0
  - env: TEST_DIR=. COMPOSER_FLAGS="--prefer-lowest"
    php: 7.0
  - env: TEST_DIR=.
    php: 7.1
  - env: TEST_DIR=. COMPOSER_FLAGS="--prefer-lowest"
    php: 7.1
  - env: TEST_DIR=.
    php: 7.2
  - env: TEST_DIR=. COMPOSER_FLAGS="--prefer-lowest"
    php: 7.2
  - env: TEST_DIR=.
    php: 7.3
  - env: TEST_DIR=. COMPOSER_FLAGS="--prefer-lowest"
    php: 7.3

before_install:
- composer self-update

install:
- composer update -o $COMPOSER_FLAGS

script:
- ./vendor/bin/phpunit

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
